from discord.ext import commands
import discord

class Tutorials(commands.Cog):
    def __init__(self, bot):
        self.bot = bot

    @commands.command(aliases=["tutorial"])
    async def tutorials(self, ctx, *args):
        if args == ():
            embed = discord.Embed(title="Tutorials", description="**Basics**\nVariables, data types, operators, conditions, loops...\n\n**Intermediate**\nClasses, modules, dates, json...", colour=discord.Colour.teal())
            embed.set_footer(text="py tutorials {category}")
            await ctx.send(embed=embed)
        else:
            args = ' '.join(args).lower()
            if "basics" in args or "basic" in args:
                embed = discord.Embed(title="Basics", description="**Variables**\nContainers for storing data values.\n\n**Data Types**\nDifferent types and their categories.\n\n**Operators**\nPerform operations on variables.\n\n**Conditions**\nIf...Else\n\n**Loops**\nWhile, For...\n\n**Functions**\nBlock of code that runs when it is called", colour=discord.Colour.teal())
                embed.set_thumbnail(
                    url="https://opensource.com/sites/default/files/styles/image-full-size/public/lead-images/python_programming_question.png?itok=cOeJW-8r")
                embed.set_footer(text="py tutorials {category}")
                await ctx.send(embed=embed)
            elif "intermediate" in args or "intermiedate" in args:
                embed = discord.Embed(title="Intermediate", description="**Classes/Objects**\nObject constructor\n\n**Modules**\nCode libraries\n\n**Dates**\nDatetime module\n\n**JSON**\nStore and exchange small data", colour=discord.Colour.orange())
                embed.set_thumbnail(
                    url="https://assetsds.cdnedge.bluemix.net/sites/default/files/styles/amp_metadata_content_image_min_696px_wide/public/feature/images/3094291_0.jpg?itok=xnOEF_vP")
                embed.set_footer(text="py tutorials {category}")
                await ctx.send(embed=embed)
            elif "variables" in args or "variable" in args:
                embed = discord.Embed(title="Variables", description="Variables are containers for storing data values.\n Python has no command for declaring a variable. A variable is created the moment you first assign a value to it.\n\n**Example:**\n```x = 5\ny = 'John'```\n\nVariables do not need to be declared with any particular type, and can even change type after they have been set.", colour=discord.Colour.teal())
                await ctx.send(embed=embed)
            elif "data" in args and "types" in args or "datatypes" in args or "data" and "type" in args:
                embed = discord.Embed(title="Data Types", description="In programming, data type is an important concept.\nVariables can store data of different types, and different types can do different things.\nPython has the following data types built-in by default, in these categories:\n\n**Text Type:** `str`\n**Numeric Types:** `int`, `float`, `complex`\n**Sequence Types:** `list`, `tuple`, `range`\n**Mapping Type:** `dict`\n**Set Types:** `set`, `frozenset`\n**Boolean Type:** `bool`\n\nYou can get the data type of any object by using the type() function\n\n**Example:**\n```x = 5\nprint(type(x))```", colour=discord.Colour.teal())
                await ctx.send(embed=embed)
            elif "operators" in args or "operator" in args:
                embed = discord.Embed(title="Operators", description="Operators are used to perform operations on variables and values. In the example below, we use the + operator to add together two values\n\n**Example:**\n```print(10 + 5)```\n\n**Arithmetic operators**\nArithmetic operators are used with numeric values to perform common mathematical operations\n\n**Assignment operators**\nAssignment operators are used to assign values to variables\n\n**Comparison operators**\nComparison operators are used to compare two values\n\n**Logical operators**\nLogical operators are used to combine conditional statements\n\n**Identity Operators**\nIdentity operators are used to compare the objects, not if they are equal, but if they are actually the same object, with the same memory location\n\n**Membership operators**\nMembership operators are used to test if a sequence is presented in an object\n\nUse `tutorial operator {operator category}` for more info.", colour=discord.Colour.teal())
                await ctx.send(embed=embed)
            elif "condition" in args or "conditions" in args:
                embed = discord.Embed(title="Conditions", description='**If statement**\nAn __if statement__ is written by using the `if` keyword.\n\n```\na = 33\nb = 200\nif b > a:\n   print("b is greater than a")\n```\nIn this example we use two variables, a and b, which are used as part of the if statement to test whether b is greater than a. As a is 33, and b is 200, we know that 200 is greater than 33, and so we print to screen that "b is greater than a".\n\n**Elif statement**\nThe `elif` keyword is pythons way of saying "if the previous conditions were not true, then try this condition".\n\n```\na = 33\nb = 33\nif b > a:\n  print("b is greater than a")\nelif a == b:\n  print("a and b are equal")\n```\n\n**Else statement**\nThe `else` keyword catches anything which isn\'t caught by the preceding conditions.\n\n```\na = 200\nb = 33\nif b > a:\n  print("b is greater than a")\nelif a == b:\n  print("a and b are equal")\nelse:\n  print("a is greater than b")\n```\n\n**Indentation**\nPython relies on indentation (whitespace at the beginning of a line) to define scope in the code.', colour=discord.Colour.teal())
                await ctx.send(embed=embed)
            elif "loop" in args or "loops" in args:
                embed = discord.Embed(title="Loops", description='Python has two primitive loop commands:\n> `while` loops\n> `for` loops\n\n**While loop**\nWith the `while` loop we can execute a set of statements as long as a condition is true.\nPrint i as long as i is less than 6:\n```\ni = 1\nwhile i < 6:\n  print(i)\n  i += 1\n```\n\n**For loop**\nA for loop is used for iterating over a sequence (that is either a list, a tuple, a dictionary, a set, or a string).\nWith the for loop we can execute a set of statements, once for each item in a list, tuple, set etc.\nPrint each fruit in a fruit list:\n```\nfruits = ["apple", "banana", "cherry"]\nfor x in fruits:\n  print(x)\n```\n\n**Break statement**\nWith the `break` statement we can stop the loop even if the while condition is true.\nExit the loop when i is 3:\n```\ni = 1\nwhile i < 6:\n  print(i)\n  if i == 3:\n    break\n  i += 1\n```\n\n**Continue statement**\nWith the `continue` statement we can stop the current iteration of the loop, and continue with the next:\n```\nfruits = ["apple", "banana", "cherry"]\nfor x in fruits:\n  if x == "banana":\n    continue\n  print(x)\n```', colour=discord.Colour.teal())
                await ctx.send(embed=embed)
            elif "function" in args or "functions" in args:
                embed = discord.Embed(title="Functions", description='A function is a block of code which only runs when it is called.\nYou can pass data, known as parameters, into a function.\nA function can return data as a result.\n\nA function is defined using the `def` keyword:\n```\ndef my_function():\n  print("Hello from a function")\n```\n\nTo call a function, use the function name followed by parenthesis:\n```\nmy_function()\n```\n\n**Arguments**\nInformation can be passed into functions as arguments. Arguments are specified after the function name, inside the parentheses. You can add as many arguments as you want, just separate them with a comma.\n```\ndef my_function(fruit):\n   print("The fruit is " + fruit)\n\nmy_function("apple")\n```\n\n**Number of arguments**\nBy default, a function must be called with the correct number of arguments. Meaning that if your function expects 2 arguments, you have to call the function with 2 arguments, not more, and not less.\nThis function expects 2 arguments, and gets 2 arguments:\n```\ndef my_function(fname, lname):\n  print(fname + " " + lname)\nmy_function("Carl", "Jeffrey")\n```\nIf you try to call the function with 1 or 3 arguments, you will get an error.\n\n**Return values**\nTo let a function return a value, use the return statement:\n```\ndef my_function(x):\n  return 5 * x\nprint(my_function(3))\nprint(my_function(5))\n```', colour=discord.Colour.teal())
                await ctx.send(embed=embed)
            elif "class" in args or "classes" in args or "object" in args or "objects" in args:
                embed = discord.Embed(title="Classes/Objects", description='To create a class, use the keyword `class`:\nCreate a class named MyClass, with a property named x:\n```\nclass MyClass:\n  x = 5\n```\nNow we can use the class named MyClass to create objects:\nCreate an object named p1, and print the value of x:\n```\np1 = MyClass()\nprint(p1.x)\n```\n\n**The \_\_init\_\_() function**\nTo understand the meaning of classes we have to understand the built-in \_\_init\_\_() function.\nAll classes have a function called \_\_init\_\_(), which is always executed when the class is being initiated.\nUse the \_\_init\_\_() function to assign values to object properties, or other operations that are necessary to do when the object is being created:\n```\nclass Person:\n  def __init__(self, name, age):\n    self.name = name\n    self.age = age\np1 = Person("John", 36)\nprint(p1.name)\nprint(p1.age)\n```\n**The self parameter**\nThe `self` parameter is a reference to the current instance of the class, and is used to access variables that belongs to the class.\nIt does not have to be named `self`, you can call it whatever you like, but it has to be the first parameter of any function in the class.\n\n**Modify object properties**\nYou can modify properties on objects like this:\nSet the age of p1 to 40:\n```\np1.age = 40\n```\n**Delete object properties**\nYou can delete properties on objects by using the del keyword:\nDelete the age property from the p1 object:\n```\ndel p1.age\n```', colour=discord.Colour.orange())
                await ctx.send(embed=embed)
            elif "datetime" in args or "date" in args or "date" in args and "time" in args:
                embed = discord.Embed(title="Datetime", description='A date in Python is not a data type of its own, but we can import a module named datetime to work with dates as date objects.\n\nImport the datetime module and display the current date:\n```\nimport datetime\n\nx = datetime.datetime.now()\nprint(x)\n```\nWhen we execute the code from the example above the result will be `2021-03-25 19:24:31.217979`\nThe date contains year, month, day, hour, minute, second, and microsecond.\nReturn the year and name of weekday:\n```\nimport datetime\nx = datetime.datetime.now()\nprint(x.year)\nprint(x.strftime("%A"))\n```\nTo create a date, we can use the datetime() class (constructor) of the datetime module.\n\nThe **datetime()** class requires three parameters to create a date: year, month, day.\n```\nimport datetime\n\nx = datetime.datetime(2021, 5, 17)\n\nprint(x)\n```\nThe datetime() class also takes parameters for time and timezone (hour, minute, second, microsecond, tzone), but they are optional, and has a default value of 0, (None for timezone).', colour=discord.Colour.teal())
                await ctx.send(embed=embed)
            elif "module" in args or "modules" in args:
                embed = discord.Embed(title="Modules", description='Consider a module to be the same as a code library.\nA file containing a set of functions you want to include in your application.\n\nTo create a module just save the code you want in a file with the file extension `.py`:\nSave this code in a file named mymodule.py\n```\ndef greeting(name):\n  print("Hello, " + name)\n```\nNow we can use the module we just created, by using the `import` statement:\nImport the module named mymodule, and call the greeting function:\n```\nimport mymodule\n\nmymodule.greeting("John")\n```\n> When using a function from a module, use the syntax: module_name.function_name\n\n**Variables in modules**\nThe module can contain functions, as already described, but also variables of all types:\nSave this code in the file mymodule.py\n```\nperson1 = {\n  "name": "John",\n  "age": 36,\n  "country": "Norway"\n}\n```\nImport the module named mymodule, and access the person1 dictionary:\n```\nimport mymodule\na = mymodule.person1["age"]\nprint(a)\n```\nYou can name a module whatever you like, but it must have the file extension `.py`\n\n**Import from module**\nYou can choose to import only parts from a module, by using the from keyword.\nImport only the person1 dictionary from the module:\n```\nfrom mymodule import person1\n\nprint(person1["age"])\n```', colour=discord.Colour.orange())
                await ctx.send(embed=embed)
            elif "json" in args:
                embed = discord.Embed(title="JSON", description='JSON is a syntax for storing and exchanging data. It is text, written with JavaScript object notation.\n\nPython has a built-in package called `json`, which can be used to work with JSON data: `import json`\n**Parse JSON - Convert from JSON to Python**\nIf you have a JSON string, you can parse it by using the `json.loads()` method.\n\n```\nimport json\n# some JSON:\nx = \'{ "name":"John", "age":30, "city":"New York"}\'\n# parse x:\ny = json.loads(x)\n# the result is a Python dictionary:\nprint(y["age"])\n```\n**Convert from Python to JSON**\nIf you have a Python object, you can convert it into a JSON string by using the json.dumps() method.\n\n```\nimport json\n# a Python object (dict):\nx = {\n  "name": "John",\n  "age": 30,\n  "city": "New York"\n}\n# convert into JSON:\ny = json.dumps(x)\n# the result is a JSON string:\nprint(y)\n```\n**Read and write to a JSON file**\n```\nimport json\n\nwith open("animals.json") as file:\n   animals = json.load(file) # Read file\nanimals["animals"] = ["dog", "cat"] # Change the list\nprint(animals["animals])\n\nwith open("animals.json", "w") as file:\n   json.dump(animals, file  # Write the new list to the file\n```', colour=discord.Colour.teal())
                await ctx.send(embed=embed)
            elif "arithmetic" in args and "operator" in args or "arithmetic" in args and "operators" in args:
                embed = discord.Embed(title="Arithmetic operators", description="Operator | Name\n\n> **+**   Addition\n> **-**   Subtraction\n> *****   Multiplication\n> **/**   Division\n> **%**   Modulus\n> ******   Exponentiation\n> **//**   Floor division", colour=discord.Colour.teal())
                await ctx.send(embed=embed)
            elif "assignment" in args and "operator" in args or "assignment" in args and "operators" in args:
                embed = discord.Embed(title="Assignment operators", description="Operator\n\n> **=**\n> **+=**\n> **-=**\n> *****\n> **/=**\n> **%=**\n> **//**\n> ****=**", colour=discord.Colour.teal())
                await ctx.send(embed=embed)
            elif "comparison" in args and "operator" in args or "comparison" in args and "operators" in args:
                embed = discord.Embed(title="Comparison operators", description="Operator | Name\n\n> **==**    Equal\n> **!=**    Not equal\n> **>**    Great than\n> **<**    Less than\n> **>=**   Greater than or equal to\n> **<=**   Less than or equal to", colour=discord.Colour.teal())
                await ctx.send(embed=embed)
            elif "logical" in args and "operator" in args or "logical" in args and "operators" in args:
                embed = discord.Embed(title="Logical operators", description="Operator | Description\n\n> **and**     Returns True if both\n>       statements are true\n> **or**     Returns True if one\n>       of the statements is true\n> **not**    Reverse the result, returns\n>       False if the result is true", colour=discord.Colour.teal())
                await ctx.send(embed=embed)
            elif "identity" in args and "operator" in args or "identity" in args and "operators" in args:
                embed = discord.Embed(title="Identity operators", description="Operator | Description\n\n> **is**    Returns True if both\n>      variables are the same object\n> **is not**  Returns True if both\n>      variables are not the same object", colour=discord.Colour.teal())
                await ctx.send(embed=embed)
            elif "membership" in args and "operator" in args or "membership" in args and "operators" in args:
                embed = discord.Embed(title="Membership operators", description="Operator | Description\n\n> **in**   Returns True if a sequence with\n>  the specified value is present in the object\n> **not in**  Returns True if a sequence with\n>  the specified value is present in the object", colour=discord.Colour.teal())
                await ctx.send(embed=embed)
            else:
                await ctx.send("That category does not exist. Make sure you spelled it right.")

def setup(bot):
    bot.add_cog(Tutorials(bot))
